
export const BACKEND_URL = "http://192.168.1.34:8080";

export const BOOKMARKS_ENDPOINT_BASE = BACKEND_URL + "/api/bookmarks";

export const BOOKMARKS_ENDPOINT_GET_ALL = BOOKMARKS_ENDPOINT_BASE;

export const BOOKMARKS_ENDPOINT_UPDATE = BOOKMARKS_ENDPOINT_BASE + "/update";

export const BOOKMARKS_ENDPOINT_DELETE = BOOKMARKS_ENDPOINT_BASE + "/delete/";

export const BOOKMARKS_ENDPOINT_ADD = BOOKMARKS_ENDPOINT_BASE + "/add";