
export const BACKEND_URL = process.env.REACT_APP_BACKEND_URL || "http://192.168.1.34:8080";

export const API_ENDPOINT_BASE = BACKEND_URL + "/api";

export const BOOKMARKS_ENDPOINT_BASE = API_ENDPOINT_BASE + "/bookmarks";

export const BOOKMARKS_ENDPOINT_GET_BY_ID = BOOKMARKS_ENDPOINT_BASE + "/";

export const BOOKMARKS_ENDPOINT_GET_ALL = BOOKMARKS_ENDPOINT_BASE;

export const BOOKMARKS_ENDPOINT_GET_BY_TAG = BOOKMARKS_ENDPOINT_BASE + "/bytag/";

export const BOOKMARKS_ENDPOINT_GET_BY_DATE = BOOKMARKS_ENDPOINT_BASE + "/bydate/";

export const BOOKMARKS_ENDPOINT_SEARCH = BOOKMARKS_ENDPOINT_BASE + "/search/";

export const BOOKMARKS_ENDPOINT_FILTER = BOOKMARKS_ENDPOINT_BASE + "/filter";

export const BOOKMARKS_ENDPOINT_UPDATE = BOOKMARKS_ENDPOINT_BASE + "/update";

export const BOOKMARKS_ENDPOINT_DELETE = BOOKMARKS_ENDPOINT_BASE + "/delete/";

export const BOOKMARKS_ENDPOINT_ADD = BOOKMARKS_ENDPOINT_BASE + "/add";

export const TAGS_ENDPOINT_BASE = BACKEND_URL + "/api/tags";

export const TAGS_ENDPOINT_GET_ALL = TAGS_ENDPOINT_BASE;

export const DATES_ENDPOINT_BASE = BACKEND_URL + "/api/dates";

export const DATES_ENDPOINT_RANGE = DATES_ENDPOINT_BASE + "/range/";

export const COMMENTS_ENDPOINTS_BASE = API_ENDPOINT_BASE + "/comments";

export const COMMENTS_ENDPOINTS_ADD = COMMENTS_ENDPOINTS_BASE + "/add";

export const COMMENTS_ENDPOINTS_GET_BY_ID = COMMENTS_ENDPOINTS_BASE + "/";

export const COMMENTS_ENDPOINTS_UPDATE_BY_ID = COMMENTS_ENDPOINTS_BASE + "/";

export const COMMENTS_ENDPOINTS_DELETE_BY_ID = COMMENTS_ENDPOINTS_BASE + "/";


// Users

export const USERS_ENDPOINT_BASE = API_ENDPOINT_BASE + "/users";

export const USERS_ENDPOINT_LIST = USERS_ENDPOINT_BASE + "/";

export const USERS_ENDPOINT_ADD = USERS_ENDPOINT_BASE + "/add";

export const USERS_ENDPOINT_EDIT = USERS_ENDPOINT_BASE + "/edit";

export const USERS_ENDPOINT_DELETE = USERS_ENDPOINT_BASE + "/delete";

export const USERS_ENDPOINT_GETBYID = USERS_ENDPOINT_BASE + "/";

// Roles

export const ROLES_ENDPOINT_BASE = API_ENDPOINT_BASE + "/roles";

export const ROLES_ENDPOINT_LIST = ROLES_ENDPOINT_BASE + "/";

export const ROLES_ENDPOINT_ADD = ROLES_ENDPOINT_BASE + "/add";

export const ROLES_ENDPOINT_EDIT = ROLES_ENDPOINT_BASE + "/edit";

export const ROLES_ENDPOINT_DELETE = ROLES_ENDPOINT_BASE + "/delete";

export const ROLES_ENDPOINT_GETBYID = ROLES_ENDPOINT_BASE + "/";

// Authentication

export const AUTHENTICATION_ENDPOINT_BASE = API_ENDPOINT_BASE + "/auth";

export const AUTHENTICATION_ENDPOINT_LOGIN = AUTHENTICATION_ENDPOINT_BASE + "/login";

export const AUTHENTICATION_ENDPOINT_LOGOUT = AUTHENTICATION_ENDPOINT_BASE + "/logout";

export const AUTHENTICATION_ENDPOINT_REGISTER = AUTHENTICATION_ENDPOINT_BASE + "/register";