
export const BACKEND_URL = process.env.REACT_APP_BACKEND_URL || "http://192.168.1.34:8080";

export const API_ENDPOINT_BASE = BACKEND_URL + "/api";

export const BOOKMARKS_ENDPOINT_BASE = API_ENDPOINT_BASE + "/bookmarks";

export const BOOKMARKS_ENDPOINT_GET_BY_ID = BOOKMARKS_ENDPOINT_BASE + "/";

export const BOOKMARKS_ENDPOINT_GET_ALL = BOOKMARKS_ENDPOINT_BASE;

export const BOOKMARKS_ENDPOINT_GET_BY_TAG = BOOKMARKS_ENDPOINT_BASE + "/bytag/";

export const BOOKMARKS_ENDPOINT_GET_BY_DATE = BOOKMARKS_ENDPOINT_BASE + "/bydate/";

export const BOOKMARKS_ENDPOINT_SEARCH = BOOKMARKS_ENDPOINT_BASE + "/search/";

export const BOOKMARKS_ENDPOINT_FILTER = BOOKMARKS_ENDPOINT_BASE + "/filter";

export const BOOKMARKS_ENDPOINT_UPDATE = BOOKMARKS_ENDPOINT_BASE + "/update";

export const BOOKMARKS_ENDPOINT_DELETE = BOOKMARKS_ENDPOINT_BASE + "/delete/";

export const BOOKMARKS_ENDPOINT_ADD = BOOKMARKS_ENDPOINT_BASE + "/add";

export const TAGS_ENDPOINT_BASE = BACKEND_URL + "/api/tags";

export const TAGS_ENDPOINT_GET_ALL = TAGS_ENDPOINT_BASE;

export const DATES_ENDPOINT_BASE = BACKEND_URL + "/api/dates";

export const DATES_ENDPOINT_RANGE = DATES_ENDPOINT_BASE + "/range/";

export const COMMENTS_ENDPOINTS_BASE = API_ENDPOINT_BASE + "/comments";

export const COMMENTS_ENDPOINTS_ADD = COMMENTS_ENDPOINTS_BASE + "/add";

export const COMMENTS_ENDPOINTS_GET_BY_ID = COMMENTS_ENDPOINTS_BASE + "/";

export const COMMENTS_ENDPOINTS_UPDATE_BY_ID = COMMENTS_ENDPOINTS_BASE + "/";

export const COMMENTS_ENDPOINTS_DELETE_BY_ID = COMMENTS_ENDPOINTS_BASE + "/";
